# Generated by Django 3.2.16 on 2023-10-24 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_staking', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userposition',
            old_name='user',
            new_name='owner',
        ),
        migrations.RenameField(
            model_name='wallet',
            old_name='user',
            new_name='owner',
        ),
    ]
