# Generated by Django 3.2.16 on 2023-10-25 10:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto_staking', '0003_auto_20231024_1944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cryptouser',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='wallet',
            name='balance',
        ),
    ]
